import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { leadId, context } = await req.json();
    
    console.log('Draft email function called for leadId:', leadId);
    
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    
    if (!LOVABLE_API_KEY) {
      console.error('LOVABLE_API_KEY not configured');
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get lead information
    const { data: lead, error: leadError } = await supabase
      .from('leads')
      .select('*')
      .eq('id', leadId)
      .single();

    if (leadError) {
      console.error('Lead fetch error:', leadError);
      throw new Error(`Lead not found: ${leadError.message}`);
    }

    console.log('Drafting email for lead:', lead.name);

    // Generate email with Gemini
    const prompt = `Draft a professional, personalized outreach email for the following lead:

Name: ${lead.name}
Company: ${lead.company || 'Unknown'}
Industry: ${lead.industry || 'Unknown'}
Notes: ${lead.notes || 'No additional notes'}
${context ? `Additional context: ${context}` : ''}

The email should:
- Be concise (under 150 words)
- Have a compelling subject line
- Personalize based on their industry/company
- Include a clear call-to-action
- Sound natural and conversational

Format the response as JSON with "subject" and "body" fields.`;

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: 'You are an assistant that drafts short, professional outreach emails. Always return only valid JSON with fields "subject" and "body".' },
          { role: 'user', content: prompt }
        ],
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        throw new Error('AI rate limits exceeded, please try again later.');
      }
      if (response.status === 402) {
        throw new Error('AI credits exhausted. Please add funds to your Lovable AI workspace.');
      }
      const errorText = await response.text();
      console.error('AI gateway error:', response.status, errorText);
      throw new Error(`AI gateway failed: ${errorText}`);
    }

    const data = await response.json();
    const generatedText = data.choices?.[0]?.message?.content ?? '';
    console.log('Email content generated by AI');

    // Parse JSON from response
    const jsonMatch = generatedText.match(/\{[\s\S]*\}/);
    let emailContent;
    
    if (jsonMatch) {
      emailContent = JSON.parse(jsonMatch[0]);
    } else {
      emailContent = {
        subject: 'Quick question about your business',
        body: generatedText
      };
    }

    // Create email campaign draft
    const { data: campaign, error: campaignError } = await supabase
      .from('email_campaigns')
      .insert({
        lead_id: leadId,
        subject: emailContent.subject,
        body: emailContent.body,
        draft_status: 'draft',
        agent_notes: 'Auto-generated by AI assistant'
      })
      .select()
      .single();

    if (campaignError) throw campaignError;

    // Create approval action
    await supabase
      .from('agent_actions')
      .insert({
        action_type: 'email_draft',
        agent_type: 'email_assistant',
        status: 'pending',
        requires_approval: true,
        data: {
          campaign_id: campaign.id,
          lead_id: leadId
        }
      });

    console.log('Email draft created:', campaign.id);

    return new Response(
      JSON.stringify({ success: true, campaign }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Draft email error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    console.error('Error details:', errorMessage);
    return new Response(
      JSON.stringify({ 
        error: errorMessage,
        details: error instanceof Error ? error.stack : undefined
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
